### Base Variables
@baseUrl = http://localhost:3000/api/v1
@contentType = application/json

# ==========================================
# TEST 1: Onboard a New Tenant (Logistics Company)
# ==========================================
# @name onboardTenant
POST {{baseUrl}}/tenants/onboard
Content-Type: {{contentType}}

{
  "companyName": "Eldios Enterprices",
  "subdomain": "eldios-team",
  "industry": "Sport",
  "adminEmail": "Eldios50@gmail.com",
  "adminPassword": "AdminPassword123!"
}
